In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing the data:

In [2]:
dataset = pd.read_csv("/Users/aryanmishra/Desktop/TF/UDEMY COURSE 1/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")
dataset #A pandas dataframes

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Need to find relation between features (country, age, salary) and the dependent variable Purchased

In [4]:
x = dataset.iloc[:,:-1] #syntax - datframe.iloc[ slice of rows, slice of columns]
y = dataset.iloc[:,-1:]
x,y

(   Country   Age   Salary
 0   France  44.0  72000.0
 1    Spain  27.0  48000.0
 2  Germany  30.0  54000.0
 3    Spain  38.0  61000.0
 4  Germany  40.0      NaN
 5   France  35.0  58000.0
 6    Spain   NaN  52000.0
 7   France  48.0  79000.0
 8  Germany  50.0  83000.0
 9   France  37.0  67000.0,
   Purchased
 0        No
 1       Yes
 2        No
 3        No
 4       Yes
 5       Yes
 6        No
 7       Yes
 8        No
 9       Yes)

x,y are dataframes.
To make it into an array of values, we use datframe.values command - returns a 2d array with ros as elements and column values as elements of rows.
store them in X and Y

In [5]:
X = x.values
Y = y.values
X,Y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array([['No'],
        ['Yes'],
        ['No'],
        ['No'],
        ['Yes'],
        ['Yes'],
        ['No'],
        ['Yes'],
        ['No'],
        ['Yes']], dtype=object))

Taking Care of Missing Data:

The classic way to handle the missing data is to replace the missing points with average of the values that are in the columns of the missing data point

We start with use of scikit learn

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X
#imputer is an object of the simple imputer class


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding Categorical Data:

Give the strings a weight.
Cannot give the weights simply to the names of the countries. We need to let the machine independently figure out what the output is going to be.
Give Binary vector encodings to the string parameters.
Eg : France : 100, Spain : 010, Germany : 001

use column transform class of compose module of sklearn library
use onehotencoding from preprocessing module of sklearn library

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [("encoder", OneHotEncoder(), [0])], remainder= "passthrough")
#transformers - need a list of the type of encoding, the encoder, and the list of indeces where you want to apply OHE
#Remainder to tell the object to return the original columns too...
#ct has a method fit_transform
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

Encoding the dependent variable
Difference between Onehotencoding  and label encoder
Onehotencoder when you have several(3+) categories in the data. Label Encoder when we have only 2 categories in dataframe/ dataset


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

Splitting data set into train and test data set:
Separate the dataset into a training set to train the model and then a test data set to test the model on new, unseen data.

In [9]:
#split data set into x_train, x_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)
#to make sure random factors in the tutors and my codes are the same for selecting the parameters
print(X_train)


[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [10]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [11]:
print(y_train)


[0 1 0 0 1 1 0 1]


In [12]:
print(y_test)

[0 1]


Feature Scaling : Simply consists of scaling all the variables and features. That is we want to scale the features so that the model does not make one feature more valuable than the other, that is we want all of them to be seen of the same importance.

Reason of why we use feature scaling AFTER separating the set into test and train sets. Test set is supposed to be brunt new dataset
Test set is only not to be trained with. Test set shouldnt have feature scaling with the training set. Cause scaling will have information from test set, so we have kind of "Grabbed" some information from the test set.


Feature scaling =>
Standardisation : X_stand = (x- mean(x))/(standard_eviation(x))

Normalisation : X_norm = (x-min(x))/(max(x)- min(x))

Normalisation works well when we have normal distribution in all our features.
Standardisation works well all the time.

In [90]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

Do we have to apply feature scaling to dummy variables in the data set?
Answer is no.
Reason being that we want all features to have values in the same range. Standardisation keeps the value between -3 and +3, and since dummy variables are between -3 and +3, we neednt do anything. We dont wanna lose the interpretation that every country has.

In [91]:
X_train[:,-2:] = sc.fit_transform(X_train[:,-2:])# Fit method computes mean and standard deviation of the age & salary  
#transform will apply the formula of standardisation to X_train columns and substitute them in X
#Trainer and test set need same scaler
X_test[:,-2:] = sc.fit_transform(X_test[:,-2:]) #both xtest and xtrain have same scaler

print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
